##4.1 Exercise on Functions:

###Task-1:

In [1]:
def convert_units(value, from_unit, to_unit):
    """
    Converts a given value from one unit to another.

    Args:
        value (float): The numeric value to convert.
        from_unit (str): The unit from which to convert (e.g., 'm', 'ft', 'kg', 'lbs', 'L', 'gal').
        to_unit (str): The unit to which to convert (e.g., 'm', 'ft', 'kg', 'lbs', 'L', 'gal').

    Returns:
        float: The converted value.

    Raises:
        ValueError: If the conversion between the specified units is not supported.
    """
    # Length Conversions
    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084
    elif from_unit == 'ft' and to_unit == 'm':
        return value * 0.3048

    # Weight Conversions
    elif from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value * 0.453592

    # Volume Conversions
    elif from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172
    elif from_unit == 'gal' and to_unit == 'L':
        return value * 3.78541
    else:
        raise ValueError(f"Unsupported conversion: {from_unit} to {to_unit}")

def main():
    print("Welcome to the Unit Conversion Program!")

    while True:
        print("\nChoose the type of conversion:")
        print("1. Length (m/ft)")
        print("2. Weight (kg/lbs)")
        print("3. Volume (L/gal)")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == '4':
            print("Exiting program. Goodbye!")
            break

        conversion_map = {
            '1': {'type': 'Length', 'units': ['m', 'ft']},
            '2': {'type': 'Weight', 'units': ['kg', 'lbs']},
            '3': {'type': 'Volume', 'units': ['L', 'gal']}
        }

        if choice not in conversion_map:
            print("Invalid choice. Please enter a number between 1 and 4.")
            continue

        conv_type_info = conversion_map[choice]
        unit1, unit2 = conv_type_info['units']

        from_unit_input = input(f"Enter the unit you want to convert from ({unit1}/{unit2}): ").strip().lower()
        to_unit_input = input(f"Enter the unit you want to convert to ({unit1}/{unit2}): ").strip().lower()

        if not ((from_unit_input == unit1 and to_unit_input == unit2) or
                (from_unit_input == unit2 and to_unit_input == unit1)):
            print("Invalid unit combination for this conversion type. Please try again.")
            continue

        try:
            value_str = input(f"Enter the value in {from_unit_input} to convert: ")
            value = float(value_str)

            result = convert_units(value, from_unit_input, to_unit_input)
            print(f"{value} {from_unit_input} is equal to {result:.4f} {to_unit_input}")
        except ValueError as e:
            print(f"Error: {e}. Please ensure you enter a numeric value and valid units.")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

if __name__ == '__main__':
    main()

Welcome to the Unit Conversion Program!

Choose the type of conversion:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (L/gal)
4. Exit
Enter your choice (1-4): 1
Enter the unit you want to convert from (m/ft): m
Enter the unit you want to convert to (m/ft): ft
Enter the value in m to convert: 200
200.0 m is equal to 656.1680 ft

Choose the type of conversion:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (L/gal)
4. Exit
Enter your choice (1-4): 4
Exiting program. Goodbye!


###Task-2:

In [2]:
def sum(numbers:list)->int:
  '''
  A function that takes a list of numbers and returns the sum of the numbers.
  Args:
    numbers: A list of numbers.
  Returns:
    The sum of the numbers.
  '''
  output = 0
  for number in numbers:
    output += number
  return output

def average(numbers:list)->float:
  '''
  A function that takes a list of numbers and returns the average of the numbers.
  Args:
    numbers: A list of numbers.
  Returns:
    The average of the numbers.
  '''
  return sum(numbers)/len(numbers)

def maximum(numbers:list)->int:
  '''
  A function that takes a list of numbers and returns the maximum of the numbers.
  Args:
    numbers: A list of numbers.
  Returns:
    The maximum of the numbers.
  '''
  output = numbers[0]
  for number in numbers:
    if number > output:
      output = number
  return output

def main():
  while True:
        print("\nChoose the operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == '4':
            print("Exiting program. Goodbye!")
            break

        numbers_str = input("Enter the numbers separated by spaces: ").split()

        try:
            numbers = [float(number) for number in numbers_str]
        except ValueError:
            print("Invalid input. Please enter valid numbers separated by spaces.")
            continue
        if not numbers:
            if choice == '1':
                print("The sum is: ", sum(numbers))
                continue
            elif choice in ['2', '3']:
                print("Cannot perform this operation on an empty list of numbers.")
                continue

        match choice:
          case "1":
            print("The sum is: ",sum(numbers))
          case "2":
            print("The average is: ",average(numbers))
          case "3":
            print("The maximum is: ",maximum(numbers))
          case _:
            print("Invalid choice. Please enter a number between 1 and 4.")
if __name__ == '__main__':
    main()



Choose the operation:
1. Sum
2. Average
3. Maximum
4. Exit
Enter your choice (1-4): 1
Enter the numbers separated by spaces: 1 2
The sum is:  3.0

Choose the operation:
1. Sum
2. Average
3. Maximum
4. Exit
Enter your choice (1-4): 4
Exiting program. Goodbye!


## 4.2 Exercise on List Manipulation:

###1. Extract Every Other Element:

In [3]:
def extract_every_other(numbers:list)->list:
  '''
  This function extracts every other element from a list of numbers.
  args:
    numbers: A list of numbers.
  returns:
    A list of every other element from the input list.
  '''
  result =[]
  count =0
  size = len(numbers)
  while count < size:

    result.append(numbers[count])
    count +=2
  return result

numbers = [1,2,3,4,5,6,7,8,9,10]
print(extract_every_other(numbers))


[1, 3, 5, 7, 9]


###2. Slice a Sublist:

In [4]:
def get_sublist(lst:list, start:int, end:int) ->list:
  '''
  This function returns a sublist of a given list.
  Args:
    lst (list): The input list.
    start (int): The starting index (inclusive) of the sublist.
    end (int): The ending index (inclusive) of the sublist.
  Returns:
    list: A new list containing the elements from the start to the end index (inclusive).

  Raises:
    ValueError: If the start or end index is out of bounds.
  '''
  if start < 0 or end >= len(lst):
    raise ValueError("Invalid start or end index")
  return lst[start:end+1]

numbers = [1,2,4,5,6,7,8,9]
try:
  print(get_sublist(numbers, 2, 5))
except ValueError as e:
  print(e)

[4, 5, 6, 7]


###3. Reverse a List Using Slicing:

In [5]:
def reverse_list(lst:list)->list:
  # Using slicing to reverse the list
  return lst[::-1]

num = [1,2,4,5]
print(reverse_list(num))

[5, 4, 2, 1]


###4. Remove the first and last element:


In [6]:
def remove_first_last(lst:list)->list:
  lst.pop(0)
  lst.pop(len(lst)-1)
  return lst

numbers = [1,2,3,4,5,6]
print(remove_first_last(numbers))

[2, 3, 4, 5]


###5. Get the first n Elements:

In [7]:
def get_first_n(n:int, lst:list)->list:
  return lst[:n]

numbers = [1,2,3,4,5]
print(get_first_n(3, numbers))



[1, 2, 3]


###6. Extract Elements from the end:

In [8]:
def get_last_n(lst:list, n:int)->list:
  return lst[-n:]

numbers = [1,2,3,4,5]
print(get_last_n(numbers, 3))

[3, 4, 5]


###7. Extract Elements in Reverse Order:

In [9]:
def reverse_skip(lst: list) -> list:
  if len(lst) < 2:
      return []
  return lst[len(lst) - 2 :: -2]

# Example usage:
numbers = [1, 2, 3, 4, 5, 6]
print(f"Original list: {numbers}")
print(f"Extracted elements in reverse order: {reverse_skip(numbers)}")



Original list: [1, 2, 3, 4, 5, 6]
Extracted elements in reverse order: [5, 3, 1]


##4.3 Exercise on Nested List:

###1. Flatten a Nested list:

In [10]:
def flatten(lst:list) ->list:
  flat = [item for sublist in lst for item in sublist]
  return flat

input = [[1, 2], [3, 4], [5]]
print(flatten(input))

[1, 2, 3, 4, 5]


###2. Accessing Nested List Elements:

In [11]:
def access_nested_element(lst:list, indices:list)->int:
  x, y = indices[0], indices[1]
  return lst[x][y]

input = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indexes = [1,2]
print(access_nested_element(input,indexes))

6


###3. Sum of All Elements in a Nested List:

In [12]:
def sum_nested(lst:list)->int:
  total = 0
  for element in lst:
    if isinstance(element, list):
      total += sum_nested(element)
    elif isinstance(element, (int, float)):
      total += element
  return total

input = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(input))

21


###4. Remove Specific Element from a Nested List:

In [13]:
def remove_element(lst:list, elem:int)->list:
  result = []
  for item in lst:
    if isinstance(item, list):
      new_sublist = [x for x in item if x != elem]
      result.append(new_sublist)
    elif item != elem:
      result.append(item)
  return result

input_user_example = [[1, 2], [3, 2], [4, 5]]
print(f"Input: {input_user_example}, Element to remove: 2, Output: {remove_element(input_user_example, 2)}")


Input: [[1, 2], [3, 2], [4, 5]], Element to remove: 2, Output: [[1], [3], [4, 5]]


###5. Find the Maximum Element in a Nested List:

In [14]:
def find_max(lst):
    stack = list(lst)
    max_val = float('-inf')

    while stack:
        item = stack.pop()
        if isinstance(item, list):
            stack.extend(item)
        else:
            if item > max_val:
                max_val = item
    return max_val

input_data = [[1, 2], [3, [4, 5]], 6]
print(find_max(input_data))

6


###6. Count Occurrences of an Element in a Nested List:

In [15]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1  # Found a match
    return count

input_data = [[1, 2], [3, [4, 5]], 6]
print(count_occurrences(input_data, 3))  # Output: 1


1


###7. Flatten a List of Lists of Lists:

In [16]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

input_data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(input_data))

[1, 2, 3, 4, 5, 6, 7, 8]


###8. Nested List Average:

In [17]:
def average_nested(lst):
    total = 0
    count = 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return total, count
total, count = average_nested([[1, 2], [3, 4], [5, 6]])
avg = total / count
print(avg)

3.5


#10 To - Do - NumPy

##10.1 Basic Vector and Matrix Operation with Numpy.


###Problem - 1: Array Creation:

In [18]:
import numpy as np
#1. Empty array
empty_arr = np.empty((2,2))
print("Empty: \n",empty_arr)

#2. all one array
all_1s_arr = np.ones((4,2))
print("All ones: \n",all_1s_arr)

#3. new array of given shape and type, filled with fill_value
new_arr = np.full((2,2), 5)
print("New: \n",new_arr)

#4. new array of zeroes with same shape and type
zeroes_arr = np.zeros_like(new_arr)
print("Zeroes: \n",zeroes_arr)

#5. new array of ones with same shape and type
ones_arr = np.ones_like(new_arr)
print("Ones: \n",ones_arr)


Empty: 
 [[6.23446617e-319 0.00000000e+000]
 [6.89455598e-310 6.89455589e-310]]
All ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
New: 
 [[5 5]
 [5 5]]
Zeroes: 
 [[0 0]
 [0 0]]
Ones: 
 [[1 1]
 [1 1]]


###Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [19]:
import numpy as np

#1. An array with values ranging from 10 to 49
first_arr = np.arange(10,50)
print("1. Array ranging from 10 to 45: \n",first_arr)

#2. a 3X3 matrix with values ranging from 0 - 8
second_arr = np.arange(0,9).reshape(3,3)
print("2. 3x3 matrix ranging from 0 - 8 \n",second_arr)

#3. 3X3 identity matrix
third_arr = np.eye(3)
print("3. 3x3 identity matrix: \n",third_arr)

#4. a random array of size 30 and find the mean of the array
fourth_arr = np.random.rand(30)
fourth_arr_mean = np.mean(fourth_arr)
print("4. Random array of size 30: \n",fourth_arr)
print("Mean of the array: \n",fourth_arr_mean)

#5. 10X10 array with random values and find max and min values
fifth_arr = np.random.rand(10,10)
fifth_arr_max = np.max(fifth_arr)
fifth_arr_min = np.min(fifth_arr)
print("5. 10x10 array with random values: \n",fifth_arr)
print("Max value of the array: \n",fifth_arr_max)
print("Min value of the array: \n",fifth_arr_min)

#6. A zero array of size 10 and replace 5th element with 1
sixth_arr = np.zeros(10)
sixth_arr[4] = 1
print("6. Zero array of size 10 with 5th element as 1: \n",sixth_arr)

#7. Reverse a array
arr = [1,2,0,0,4,0]
seventh_arr = np.array(arr)
seventh_arr = seventh_arr[::-1]
print("7. Reversed array: \n",seventh_arr)

#8. A 2d array with 1 on border and 0 inside
eight_arr = np.ones((5,5))
eight_arr[1:-1,1:-1] = 0
print("8. 2d array with 1 on border and 0 inside: \n",eight_arr)

#9. A 8X8 matrix and fill it with checeker board pattern
nine_arr = np.zeros((8,8))
nine_arr[1::2,::2] = 1
nine_arr[::2,1::2] = 1
print("9. 8x8 matrix with checkerboard pattern: \n",nine_arr)



1. Array ranging from 10 to 45: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 3x3 matrix ranging from 0 - 8 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3. 3x3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. Random array of size 30: 
 [0.63440898 0.96651825 0.29648532 0.7288057  0.74144237 0.75412698
 0.52908735 0.73352624 0.50710827 0.02636522 0.56293273 0.61365508
 0.05368603 0.89542434 0.07855704 0.73968179 0.84868176 0.74900345
 0.8825833  0.0789316  0.23618186 0.54055459 0.37761751 0.50856367
 0.31480181 0.01918701 0.8418014  0.29007692 0.26800127 0.30335563]
Mean of the array: 
 0.504038448474342
5. 10x10 array with random values: 
 [[0.58331335 0.42014051 0.25002409 0.79590579 0.14379136 0.90665081
  0.27640957 0.64787051 0.64602001 0.13814989]
 [0.43260884 0.88854958 0.45861799 0.82689645 0.16847541 0.49640506
  0.28408158 0.0075281  0.55395325 0.57329688]
 [0.6021016  0.20598435 0.71469371 0.87630403

###Problem - 3: Array Operations:

In [20]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1. add the two array
addition = np.add(x,y)
print("1. Addition of two arrays: \n", addition)

#2. subtract the two array
subtraction = np.subtract(x,y)
print("2. Subtraction of two arrays: \n", subtraction)

#3. Multiply the array with any integer
multiplication = np.multiply(v,10)
print("3. Multiplication of v arr with 10: \n",multiplication)

#4. Square each element of the array
square = np.square(x)
print("4. Square of x array: \n",square)

#5. dot product between v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v,w)
dot_xv = np.dot(x,v)
dot_xy = np.dot(x,y)
print(f"5. The dot product beteween vw, xv, xy \n vw: {dot_vw}, xv: {dot_xv}, xy: {dot_xy}  ")

#6. Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_xy_row = np.concatenate((x, y), axis=0)
print("\n6. Concatenation of x and y along row (axis=0):\n", concat_xy_row)

concat_vw_col = np.concatenate((v.reshape(1, -1), w.reshape(1, -1)), axis=1)
print("Concatenation of v and w along column (axis=1):\n", concat_vw_col)

#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    np.concatenate((x, v))
except ValueError as e:
    print(f"\n7. Error concatenating x and v: {e}")
    print("Explanation: Concatenation along an axis requires that all arrays have the same shape, except in the dimension corresponding to the axis of concatenation. Here, 'x' is a 2D array (2,2) and 'v' is a 1D array (2,). They have incompatible dimensions for concatenation without reshaping one or both to a compatible 2D form.")

1. Addition of two arrays: 
 [[ 6  8]
 [10 13]]
2. Subtraction of two arrays: 
 [[-4 -4]
 [-4 -3]]
3. Multiplication of v arr with 10: 
 [ 90 100]
4. Square of x array: 
 [[ 1  4]
 [ 9 25]]
5. The dot product beteween vw, xv, xy 
 vw: 219, xv: [29 77], xy: [[19 22]
 [50 58]]  

6. Concatenation of x and y along row (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along column (axis=1):
 [[ 9 10 11 12]]

7. Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Concatenation along an axis requires that all arrays have the same shape, except in the dimension corresponding to the axis of concatenation. Here, 'x' is a 2D array (2,2) and 'v' is a 1D array (2,). They have incompatible dimensions for concatenation without reshaping one or both to a compatible 2D form.


###Problem - 4: Matrix Operations:

In [21]:
import numpy as np

A = np.array([[3,4], [7,8]])
B = np.array([[5,3], [2,1]])

#1. A.A-1 = I
a_inv = np.linalg.inv(A)
identity_matrix = np.eye(2)
result = np.dot(A, a_inv)
isProven = np.allclose(result, identity_matrix)
print(f"1. A.A-1 = I: {isProven}")

#2. AB != BA
ab = np.dot(A,B)
ba = np.dot(B,A)
print(f"2. AB != BA: {not np.array_equal(ab, ba)}")

#3. (AB)T = Bt At
ab_transpose = np.transpose(ab)
aT = np.transpose(A)
bT = np.transpose(B)
bT_aT = np.dot(bT, aT)
print(f"3. (AB)T = Bt At: {np.array_equal(ab_transpose, bT_aT)}")

1. A.A-1 = I: True
2. AB != BA: True
3. (AB)T = Bt At: True


In [22]:
import numpy as np

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("The values of [x, y, z] are:")
print(X)

The values of [x, y, z] are:
[ 2.  1. -2.]


#10.2 Experiment: How Fast is Numpy?

###1. Element-wise Addition:

In [23]:
import numpy as np
import time

size = 1_000_000

### 1. Using Python Lists
list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
# Element-wise addition using a list comprehension
list_result = [list_a[i] + list_b[i] for i in range(size)]
list_time = time.time() - start_time

print(f"Python List Addition Time: {list_time:.5f} seconds")


### 2. Using NumPy Arrays
array_a = np.arange(size)
array_b = np.arange(size)

start_time = time.time()
# Element-wise addition using NumPy's vectorized operation
array_result = array_a + array_b
numpy_time = time.time() - start_time

print(f"NumPy Array Addition Time:  {numpy_time:.5f} seconds")

# Calculate the speedup
print(f"\nNumPy is {list_time / numpy_time:.2f}x faster than Python lists!")

Python List Addition Time: 0.20804 seconds
NumPy Array Addition Time:  0.00432 seconds

NumPy is 48.17x faster than Python lists!


###2. Element-wise Multiplication

In [24]:
import numpy as np
import time

size = 1_000_000

list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
list_result = [list_a[i] * list_b[i] for i in range(size)]
list_multi_time = time.time() - start_time

print(f"Python List Multiplication Time: {list_multi_time:.5f} seconds")


array_a = np.arange(size)
array_b = np.arange(size)

start_time = time.time()
array_result = array_a * array_b
numpy_multi_time = time.time() - start_time

print(f"NumPy Array Multiplication Time:  {numpy_multi_time:.5f} seconds")

# Calculate the speedup
speedup = list_multi_time / numpy_multi_time
print(f"\nNumPy is {speedup:.2f}x faster at multiplication!")

Python List Multiplication Time: 0.14117 seconds
NumPy Array Multiplication Time:  0.00395 seconds

NumPy is 35.71x faster at multiplication!


###3. Dot Product

In [25]:
import numpy as np
import time

size = 1_000_000

list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(list_a, list_b))
list_dot_time = time.time() - start_time

print(f"Python List Dot Product Time: {list_dot_time:.5f} seconds")

array_a = np.arange(size, dtype=np.int64)
array_b = np.arange(size, dtype=np.int64)

start_time = time.time()
dot_product_array = np.dot(array_a, array_b)
numpy_dot_time = time.time() - start_time

print(f"NumPy Array Dot Product Time:  {numpy_dot_time:.5f} seconds")

speedup = list_dot_time / numpy_dot_time
print(f"\nNumPy is {speedup:.2f}x faster at dot product!")

Python List Dot Product Time: 0.10514 seconds
NumPy Array Dot Product Time:  0.00247 seconds

NumPy is 42.50x faster at dot product!


###3. Matrix Multiplication

In [26]:
import numpy as np
import time

size = 1000

list_a = [[i for i in range(size)] for j in range(size)]
list_b = [[i for i in range(size)] for j in range(size)]
list_result = [[0 for _ in range(size)] for _ in range(size)]

start_time = time.time()
for i in range(size):
    for j in range(size):
        for k in range(size):
            list_result[i][j] += list_a[i][k] * list_b[k][j]
list_time = time.time() - start_time

print(f"Python List Matrix Multiplication Time: {list_time:.5f} seconds")

# 2. Using NumPy Arrays
array_a = np.ones((size, size))
array_b = np.ones((size, size))

start_time = time.time()
array_result = np.dot(array_a, array_b) # or array_a @ array_b
numpy_time = time.time() - start_time

print(f"NumPy Array Matrix Multiplication Time:  {numpy_time:.5f} seconds")

speedup = list_time / numpy_time
print(f"\nNumPy is {speedup:.2f}x faster at matrix multiplication!")

Python List Matrix Multiplication Time: 383.09895 seconds
NumPy Array Matrix Multiplication Time:  0.05876 seconds

NumPy is 6519.76x faster at matrix multiplication!
